site_name: Pipeline Docs
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.action.edit
    - toc.integrate
    - search.suggest

nav:
  - Home: index.md
  - API Reference:
      - Pipeline A: api/pipelines.pipeline_a.md
      - Pipeline B: api/pipelines.pipeline_b.md
      - pipeline_a.md: api-generated/pipeline_a.md
      - pipeline_b.md: api-generated/pipeline_b.md



plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
