name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write  # Required for pushing to gh-pagess

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install mkdocs mkdocstrings[python] mkdocs-material

    - name: Deploy to GitHub Pages
    
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdocs gh-deploy --force --remote-branch gh-pages --remote-name origin --message "Deploy docs"




